[package]
name = "render_to_frambuffer_and_save"
version = "0.1.0"
authors = ["TheRittler <>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

iced = "0.3"
iced_wgpu = "0.4.0"
iced_winit = "0.3.0"
png = "0.16.8"
